# Site settings
title: Thompson Docs
email: info@thompsonbrandpartners.com
description: > # this means to ignore newlines until "baseurl:"
  Open source internal documentation from Thompson Brand Partners. These documents outline the principles by which we run projects. They are intended for the educational purposes of our team and are a work in progress. 
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: ThompsonBP
github_username:  thompsonbrandpartners

# Build settings
markdown: kramdown
